### ISSUE TITLE
ini file doesn't get created by titleset wizard if it doesn't exist

### ISSUE THREAD

**Issue by grepper** [grepper/tovid#149]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on July 25, 2011 22:30:29_

If the titleset wizard is run before the 'tovid gui' is ever run, the dir and file ~/.metagui/config doesn't get created, and the wizard exits on an error.

Traceback (most recent call last):
  File "/usr/local/lib/tovid/titleset-wizard", line 1221, in \<module>
    app = Wizard(root, 'Tovid\nTitleset Wizard', img_file)
  File "/usr/local/lib/tovid/titleset-wizard", line 77, in __init__
    style.load(inifile)
  File "/usr/local/lib/python2.6/dist-packages/libtovid/metagui/support.py", line 673, in load
    font = dict(config.items('font'))
  File "/usr/lib/python2.6/ConfigParser.py", line 565, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'font'

_Original issue: http://code.google.com/p/tovid/issues/detail?id=149_

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on July 25, 2011 20:30:09_

This should be fixed in rev 3347.
I'll close this on verification.

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on August 18, 2011 06:29:59_

I haven't received an answer, but I'm going to mark this as fixed as I have tested it.

**Status:** Fixed
