### ISSUE TITLE
tix dependency not listed in wiki

### ISSUE THREAD

**Issue by grepper** [grepper/tovid#159]
_From [southi...@gmail.com](https://code.google.com/u/109945107261885243880/) on January 08, 2012 10:07:55_

Using Linux Mint 10
Installed missing listed dependencies from Software Manager, checking this list: http://tovid.wikia.com/wiki/Tovid_dependencies Downloaded tovid-0.34.tar.gz & followed instructions at: http://tovid.wikia.com/wiki/Installing_tovid All went well but when I tried to start the gui I got:

Traceback (most recent call last):
  File "/usr/local/lib/tovid/todiscgui", line 8, in \<module>
    todisc.run(sys.argv[1:])
  File "/usr/local/lib/python2.6/dist-packages/libtovid/guis/todisc.py", line 993, in run
    gui = GUI("tovid gui", 800, 660, app, icon=tovid_icon)
  File "/usr/local/lib/python2.6/dist-packages/libtovid/metagui/gui.py", line 488, in __init__
    Tix.Tk.__init__(self)
  File "/usr/lib/python2.6/lib-tk/Tix.py", line 210, in __init__
    self.tk.eval('package require Tix')
_tkinter.TclError: can't find package Tix

Got tix from Software Manager & no further problems so far (currently encoding video.m2v).

Might tix be included with python-tk in some distros? Not in Mint 10 anyway. Perhaps it should be added to the Tovid dependencies list.

Thanks for the tool - I've never had any luck creating DVDs in Linux before. Hopefully this time I'll be successful...

_Original issue: http://code.google.com/p/tovid/issues/detail?id=159_

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on January 09, 2012 21:29:12_

Thanks for pointing this out.  Added to dependency page. http://tovid.wikia.com/wiki/Tovid_dependencies#GUI

**Comment by grepper** [comment]
_From [grepper@gmail.com](https://code.google.com/u/grepper@gmail.com/) on March 25, 2012 17:40:03_

**Status:** Fixed
