### ISSUE TITLE
[todiscgui svn-r2389]: issue with "Stroke Color" button at "Submenus" tab.

### ISSUE THREAD

**Issue by grepper** [grepper/tovid#27]
_From [dan...@gmail.com](https://code.google.com/u/113834599056894001796/) on November 17, 2007 18:52:18_

The title speaks for itself: I got this issue after press it. The output
on the shell follows down:

Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1406, in __call__
    return self.func(*args)
  File "/usr/lib/python2.5/site-packages/libtovid/metagui/control.py", line
598, in change
    rgb, color = tkColorChooser.askcolor(self.get())
  File "lib-tk/tkColorChooser.py", line 62, in askcolor
    return Chooser(**options).show()
  File "lib-tk/tkCommonDialog.py", line 48, in show
    s = w.tk.call(self.command, *w._options(self.options))
TclError: unknown color name "none"
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1406, in __call__
    return self.func(*args)
  File "/usr/lib/python2.5/site-packages/libtovid/metagui/control.py", line
598, in change
    rgb, color = tkColorChooser.askcolor(self.get())
  File "lib-tk/tkColorChooser.py", line 62, in askcolor
    return Chooser(**options).show()
  File "lib-tk/tkCommonDialog.py", line 48, in show
    s = w.tk.call(self.command, *w._options(self.options))
TclError: unknown color name "none"

JFYI.

Regards,

Danilo (aka 'danpos')

_Original issue: http://code.google.com/p/tovid/issues/detail?id=25_

**Comment by grepper** [comment]
_From [wapcaplet88](https://code.google.com/u/wapcaplet88/) on November 18, 2007 12:18:22_

Thanks for reporting this. It's fixed in the current SVN version; you can patch your 
todiscgui by changing this line:

    Color('Stroke color', '-submenu-stroke-color', 'none',

to this:

    Color('Stroke color', '-submenu-stroke-color', 'black',

**Summary:** Fixed  
  **Status:** Fixed  
  **Owner:** wapcaplet88

**Comment by grepper** [comment]
_From [wapcaplet88](https://code.google.com/u/wapcaplet88/) on November 18, 2007 12:19:19_

**Summary:** [todiscgui svn-r2389]: issue with "Stroke Color" button at "Submenus" tab.

**Comment by grepper** [comment]
_From [dan...@gmail.com](https://code.google.com/u/113834599056894001796/) on November 18, 2007 16:42:37_

Thanks mate! :) I will do svn up soon.

I really appreciated very much the hard work to put tovid suite every day better.

Regards,

Danilo (aka 'danpos')
